# Базовый образ, содержащий Java 17
FROM openjdk:17-oracle

# Директория приложения внутри контейнера
WORKDIR /app

# Копирование JAR-файлов приложений в контейнер
COPY build/libs/socketclient-0.0.1-SNAPSHOT.jar app.jar

# оПРЕДЕЛЕНИЕ ПЕРЕМЕННОЙ СРЕДЫ
ENV APP_SERVER_HOST=localhost
ENV APP_SERVER_PORT=8888

# Команда для запуска приложения
CMD ["java", "-jar", "app.jar"]